---

name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ERLANG_VERSION: 23.3.4.4
    steps:
      ##
      ## Setup
      ##

      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      ##
      ## Build and push Container image
      ##

      - name: Build and push container image
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: |
            ERLANG_VERSION=${{ env.ERLANG_VERSION }}
          tags: |
            ghcr.io/djwhitt/erlang:${{ env.ERLANG_VERSION }}
            ghcr.io/djwhitt/erlang:latest
